name: Cypress tests
on: [push,pull_request]
jobs:
  Build-And-Run-Tests:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
          # Test Python and Microbit, on Ubuntu, should be all in parallel:
          testtype: ["python", "microbit"]
          # Did have Mac here, but it seems to run out of memory so taken it out:
          os: [ ubuntu-latest ]
          cypress_split: [0, 1, 2] # For parallelising the jobs, length must match the --total arg below
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
      - name: NPM Install
        # ci is better than npm install for CI jobs, apparently (quicker + more predictable):
        run: npm ci
      - name: NPM Build
        run: npm run build
      - name: NPM Linter
        run: npm run lint:check        
      - name: NPM Test (Cypress)
        run: npm run test:cypress:${{ matrix.testtype }}-only
        # pass the machine index and the total number
        env:
            SPLIT: ${{ 3 }}
            SPLIT_INDEX: ${{ matrix.cypress_split }}
            SPLIT_FILE: tests/cypress/timings/timings-${{ matrix.testtype }}.json
      - name: Upload test videos (if any)
        uses: actions/upload-artifact@v4
        # Store screenshots and videos only on failure:
        if: ${{ failure() }}
        with:
            name: cypress-screenshots-and-video-${{matrix.os}}-${{matrix.testtype}}-${{ matrix.cypress_split }}
            path: |
              tests/cypress/expected-screenshots
              tests/cypress/screenshots
              tests/cypress/videos
            if-no-files-found: ignore

