name: Playwright Tests
on: [push,pull_request]
jobs:
  test:
    timeout-minutes: 95
    # 5 minutes extra to upload videos if we fail the timeout of one hour, below
    strategy:
      fail-fast: false
      matrix:
        # We would like to include windows-latest, but it seems to time out the tests
        # My best guess is that somehow the keypresses are arriving at the terminal job
        # as the terminal shows "Terminate batch job? (Y/N)" which suggests it is getting
        # the ctrl-c keypress that is intended for the browser.  But for now, we take it out
        # because testing on Mac and Ubuntu alone is better than no tests, or tests which
        # always fail
        os: [ubuntu-latest, macos-latest]
        # For parallelising the tests:
        playwright_shard: [1, 2, 3]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests (Unix)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      shell: bash
      run: |
        jq ".scripts[\"playwright:run\"] = \"npx playwright test --shard=${{ matrix.playwright_shard }}/3\"" package.json > temp.json && mv temp.json package.json
        timeout 5400s npm run test:playwright || { echo "Test command exited or timed out"; exit 1; }
    - name: Run Playwright tests (MacOS)
      if: ${{ matrix.os == 'macos-latest' }}
      shell: bash
      run: |
        brew install coreutils
        brew install jq
        jq ".scripts[\"playwright:run\"] = \"npx playwright test --shard=${{ matrix.playwright_shard }}/3\"" package.json > temp.json && mv temp.json package.json
        gtimeout 5400s npm run test:playwright || { echo "Test command exited or timed out"; exit 1; }
    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.os }}-${{matrix.playwright_shard}}
        path: tests/playwright/html-report/
        retention-days: 30
